name = "energisystemprojekt"
uuid = "e1853b06-2e25-4a4a-97fd-f3e4bc64c0ea"
authors = ["hannaekfalth <62641422+hannaekfalth@users.noreply.github.com>"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
